app:
  name: 'Movie-service'
  version: '1.0.0'

http:
  port: '9000'

logger:
  log_level: 'debug'
  rollbar_env: 'Movie-service'

# postgres:
#   pool_max: 2

# rabbitmq:
#   rpc_server_exchange: 'rpc_server'
#   rpc_client_exchange: 'rpc_client'
